spring:
  application:
    name: rest-aplication
  datasource:
    url: jdbc:h2:file:../rest_test
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

    
swagger:
  config:
    title: 'Account rest application'
    description: 'Sample rest application'
    license: 'Apache'
    licenseUrl: 'https://www.apache.org/licenses/LICENSE-2.0'
    version: '@project.version@'